moveo:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 250  

    arm_controller:
        type: effort_controllers/JointTrajectoryController
        gains:
            joint_1: {p: 100.0, i: 0.01, d: 10.0}
            joint_2: {p: 100.0, i: 0.01, d: 10.0}
            joint_3: {p: 100.0, i: 0.01, d: 10.0}
            joint_4: {p: 10.0, i: 0, d: 1.0}
            joint_5: {p: 10.0, i: 0, d: 0.0}   
        joints:
            - joint_1
            - joint_2
            - joint_3
            - joint_4
            - joint_5
        constraints:
            joint_1:
                goal: 0.1
            joint_2:
                goal: 0.1
            joint_3:
                goal: 0.1
            joint_4:
                goal: 0.1
            joint_5:
                goal: 0.1
            goal_time: 10.0
            stopped_velocity_tolerance: 0.05
            