controller_list:
  - name: fake_modelo_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - rev2
      - rev3
      - rev4
      - rev5
      - rev6
      - rev7
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: modelo_arm
    pose: home