modelo:

  # Publish all joint states -----------------------------------
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  # Position Controllers --------------------------------------
  rev2_position_controller:
      type: effort_controllers/JointPositionController
      joint: rev2
      pid: {p: 10.0, i: 0.1, d: 0.1}
  rev3_position_controller:
      type: effort_controllers/JointPositionController
      joint: rev3
      pid: {p: 10.0, i: 0.1, d: 0.1}
  rev4_position_controller:
      type: effort_controllers/JointPositionController
      joint: rev4
      pid: {p: 10.0, i: 0.1, d: 0.1}
  rev5_position_controller:
      type: effort_controllers/JointPositionController
      joint: rev5
      pid: {p: 10.0, i: 0.1, d: 0.1}
  rev6_position_controller:
      type: effort_controllers/JointPositionController
      joint: rev6
      pid: {p: 10.0, i: 0.1, d: 0.1}
  rev7_position_controller:
      type: effort_controllers/JointPositionController
      joint: rev7
      pid: {p: 10.0, i: 0.1, d: 0.1}
